# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7af62f79d19f54eb054f8159f7e99879986a6706fcabdc2c2f475d517b722c1f66a55d3ce03aade89eb43a438a6992b5cb62711b3d91d03ed82dced68aa1f786

test:
  secret_key_base: b8ed6841ec33819b097b585022bea276144dfe2a25ee306a425dd3ef578f951f041a38011891856ef678a9f21a1b3648682a476e4acad1e85912948068879368

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
